### ISSUE TITLE
Failure to authenticate with NickServ when replying via Windows Notifications

### ISSUE THREAD

**Issue by danielcg** [rymate1234/WinIRC#21]
If you connect to a server using a registered name, NickServ will message you asking you to authenticate. This triggers a native Windows notification popup that includes a text box where you can put a reply. If I reply using the notification popup with the proper response that should authenticate for my nick, NickServ says it is an invalid command.

You can test by authenticating the normal way using the chat window, then copy the text you sent that resulted in a successful login. Reopen the app and paste that text into the reply to NickServ, and you'll see that NickServ says invalid command. I'm assuming there is an extra character or something that gets added when using the notification popup to reply to a message.

This happened with Libera and the latest version of WinIRC on Windows 11 (latest Insider Release Preview build). Please let me know if you need any more info.

**Comment by jmurth1234** [comment]
Ah, this'll be because windows notifications add in `username:` to the start of a message when in a channel to better indicate who a message is directed at

I'll remove this in a PM and make a 1.7.x release
